apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: cv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-api
  template:
    metadata:
      labels:
        app: cv-api
    spec:
      containers:
      - name: api
        image: {{ .Values.images.tags.api }}
        volumeMounts:
        - name: api-config
          mountPath: "/app/app.env"
        ports:
        - containerPort: {{ .Values.conf.api.port }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "350m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: api-config
        configMap:
          name: api-configmap