apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: cv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-api
  template:
    metadata:
      labels:
        app: cv-api
    spec:
      containers:
      - name: api
        image: lucasdatb/cv-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: API_PORT
          value: "3000"
        - name: LOG_LEVEL
          value: info
        - name: LOG_OUTPUT
          value: ""
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gorm
        - name: DB_PASSWORD
          value: "S3cretP@ssw0rd"
        - name: DB_NAME
          value: api_db
        resources:
          requests:
            memory: "64Mi"
            cpu: "350m"
          limits:
            memory: "128Mi"
            cpu: "500m"
